services:
  docker-app:
    image: docker-app:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: docker-app-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - build:/app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    networks:
      - docker-app-network
    stdin_open: true
    tty: true
    env_file:
      - .env

volumes:
  node_modules:
  build:

networks:
  docker-app-network:
    driver: bridge
